### ISSUE TITLE
[BUG] cicd-app is not supported for my usecase although it is available

### ISSUE THREAD

**Issue by AlexRieder** [SAP-samples/btp-setup-automator#180] opened 2022-06-30 10:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

CLI in general

### Current Behavior

In my usecase I want to use the Continous Integration and Delivery Service Application with plan free. Although I can see it in my subaccount the script says the usecase is not supported. 

Usecase can be found here: 
https://github.com/SAP-samples/btp-setup-automator/blob/main/usecases/released/discoverycenter/3999-kyma-day2-operations/usecase.json

My assumption is that there is a problem as there is an application named cicd-app which has the plan free and there exists a service which has also the name cicd-app which only offers the default plan. Also the syntax highlighting in the usecase says that free is not allowed as value. 

### Expected Behavior

Usecase can be executed. 

### Steps To Reproduce

1. In a global account on the live landscape
2. Run the following usecase: https://github.com/SAP-samples/btp-setup-automator/blob/main/usecases/released/discoverycenter/3999-kyma-day2-operations/usecase.json
3. The error will show up while checking if the account is sufficient for the usecase

### Logs and configuration files available?

[Services.txt](https://github.com/SAP-samples/btp-setup-automator/files/9019121/Services.txt)

**Comment by lechnerc77** [comment] 2022-07-05 08:35
The issue is fixed with commit [992d9efea1c030e24a24e814c7e849955c36672a](https://github.com/SAP-samples/btp-setup-automator/commit/992d9efea1c030e24a24e814c7e849955c36672a).

The issue was caused due to the category of the cicd app which is not `APPLICATION` but `QUOTA_BASED_APPLICATION`.

Build of new Docker image started

**Comment by lechnerc77** [comment] 2022-07-05 08:44
New Docker Image with fixes is available

**Closed by lechnerc77** 2022-07-05 08:44 UTC
Labels: bug
