### ISSUE TITLE
[BUG] CF Login not working anymore

### ISSUE THREAD

**Issue by madevr** [SAP-samples/btp-setup-automator#54] opened 2022-04-07 09:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which area is mainly impacted

Cloud Foundry setups

### Current Behavior

I ran into issues while testing again. First, it seems that if I give "cfspacename": "dev-eu10" in parameters.json, the login does not work.
Earlier, this worked, although not really – the login stopped and asked me to select a space.
 
Now, I get an error w/o having the chance to do anything:
![image](https://user-images.githubusercontent.com/2878822/162171182-cbd872c9-e6e2-4a20-b753-bd1e7799a4a5.png)

If I remove the cfspacename from parameters.json, I get the same result.
Looked at the code, and I have to admit I don’t quite understand it: https://github.com/SAP-samples/btp-setup-automator/blob/main/libs/python/helperCommandExecution.py#L34
 
To me it looks like the command variable is overwritten if the cfspacename is present. But “-s $cfspacename” could be added to the original login command. However, it seems that command is not overwritten, because the login is being executed per the cmd output in the screenshot.
So maybe cfspacename is not picket up at all? Also no success via command line argument.
 

### Expected Behavior

Login works (and ideally, space is targeted immediately as well).

**Comment by rui1610** [comment] 2022-04-07 11:31
Hi, I found a smaller bug that I've just fixed. Please check with the new docker image (around 13:45 CET). If not working, I'll need your parameters.json and the usecase.json. Please delete any passwords (if existing) from the files.

**Comment by madevr** [comment] 2022-04-07 11:44
Hi, thanks for the update, just tried again, still same error. Last commit was about 2 hours ago, is the fix already pushed?

```
{
    "usecasefile": "dev.json",
    "region": "eu10",
    "cfcliapihostregion": "eu10-004",
    "globalaccount": "7974ff10-95fe-4bfd-b97a-d3f52f5b44cd",
    "myemail": "sample@test.com",
    "loginmethod": "basicAuthentication",
    "subaccountname": "blabla-dev-eu10",
    "orgid": "ae7f8cf8-4346-4172-b409-1e168693e66e",
    "cfspacename": "dev-eu10",
    "suffixinstancename": null,
    "iashost": null
  }
```

**Comment by rui1610** [comment] 2022-04-07 12:03
Just noticed I forgot to merge my pull request :-(
I've just merged my PR now and the new docker image should be there in the next 5 - 7 minutes.

**Comment by rui1610** [comment] 2022-04-07 12:30
Ok. It seems like the parameter `"cfcliapihostregion": "eu10-004"` is causing the issue here.
Are you sure that the host region is not the default one, but the "eu10-004"?
Can you try to run the script without that parameter?

**Comment by siluski** [comment] 2022-04-07 13:15
Hey all, I'm also experiencing a bug with the CF login, though a different one. I provided the org id for my CF environment, and when it runs the use case, it correctly identifies that I have an existing CF environment, but for some reason the orgname it's pulling up is the name for my Kyma runtime environment. I'm unsure if anything changed between yesterday and today but this wasn't happening before. Below is a screenshot of the issue, my parameters, and the use case I'm using. 

Parameters :

{
  "usecasefile": "usecases/released/setup_ias.json",
  "region": "eu10",
  "globalaccount": "anthonysiluk",
  "myemail": "<mysapemail>",
  "loginmethod": "basicAuthentication",
  "subaccountname": "GeneratedSubaccount1",
  "orgid": "81ab0e53-8d27-4ca1-b91c-0ab8a58b7f4b",
  "cfspacename": null,
  "suffixinstancename": null,
  "iashost": null
}

Usecase : 

{
  "aboutThisUseCase": {
    "name": "Setup trust between SAP IAS and SAP BTP subaccount",
    "description": "This usecase provides the configuration of services to create trust between a SAP BTP subaccount and a customer IAS tenant",
    "author": "fabian.lehmann02@sap.com",
    "testStatus": "tested successfully",
    "usageStatus": "READY TO BE USED"
  },
  "services": [
    {
      "name": "xsuaa",
      "plan": "apiaccess",
      "instancename": "xsuaa_api",
      "category": "SERVICE",
      "repeatstatusrequest": 5,
      "repeatstatustimeout": 200,
      "createServiceKeys": [
        "myServiceKey1"
      ]
    }
  ],
  "admins": []
}



Screenshot :
<img width="615" alt="CF Error" src="https://user-images.githubusercontent.com/47801828/162207244-a29cbcc3-efb4-4dcd-968b-aff0817a75ef.PNG">

**Comment by siluski** [comment] 2022-04-07 13:16
Hey all, I'm also experiencing a bug with the CF login, though a different one. I provided the org id for my CF environment, and when it runs the use case, it correctly identifies that I have an existing CF environment, but for some reason the orgname it's pulling up is the name for my Kyma runtime environment. I'm unsure if anything changed between yesterday and today but this wasn't happening before. Below is a screenshot of the issue, my parameters, and the use case I'm using. 

Parameters :

{
  "usecasefile": "usecases/released/setup_ias.json",
  "region": "eu10",
  "globalaccount": "anthonysiluk",
  "myemail": "<mysapemail>",
  "loginmethod": "basicAuthentication",
  "subaccountname": "GeneratedSubaccount1",
  "orgid": "81ab0e53-8d27-4ca1-b91c-0ab8a58b7f4b",
  "cfspacename": null,
  "suffixinstancename": null,
  "iashost": null
}

Usecase : 

{
  "aboutThisUseCase": {
    "name": "Setup trust between SAP IAS and SAP BTP subaccount",
    "description": "This usecase provides the configuration of services to create trust between a SAP BTP subaccount and a customer IAS tenant",
    "author": "fabian.lehmann02@sap.com",
    "testStatus": "tested successfully",
    "usageStatus": "READY TO BE USED"
  },
  "services": [
    {
      "name": "xsuaa",
      "plan": "apiaccess",
      "instancename": "xsuaa_api",
      "category": "SERVICE",
      "repeatstatusrequest": 5,
      "repeatstatustimeout": 200,
      "createServiceKeys": [
        "myServiceKey1"
      ]
    }
  ],
  "admins": []
}



Screenshot :
<img width="615" alt="CF Error" src="https://user-images.githubusercontent.com/47801828/162207244-a29cbcc3-efb4-4dcd-968b-aff0817a75ef.PNG">

**Comment by madevr** [comment] 2022-04-07 13:33
> Ok. It seems like the parameter `"cfcliapihostregion": "eu10-004"` is causing the issue here. Are you sure that the host region is not the default one, but the "eu10-004"? Can you try to run the script without that parameter?

Yes, 100% sure. I requested this parameter. ;)

Without it, the org is not found (because it resides in eu10-004).
BTW, I think eu10-004 is positioned as the new default.

**Comment by siluski** [comment] 2022-04-07 13:54
> Hey all, I'm also experiencing a bug with the CF login, though a different one. I provided the org id for my CF environment, and when it runs the use case, it correctly identifies that I have an existing CF environment, but for some reason the orgname it's pulling up is the name for my Kyma runtime environment. I'm unsure if anything changed between yesterday and today but this wasn't happening before. Below is a screenshot of the issue, my parameters, and the use case I'm using.
> 
> Parameters :
> 
> { "usecasefile": "usecases/released/setup_ias.json", "region": "eu10", "globalaccount": "anthonysiluk", "myemail": "", "loginmethod": "basicAuthentication", "subaccountname": "GeneratedSubaccount1", "orgid": "81ab0e53-8d27-4ca1-b91c-0ab8a58b7f4b", "cfspacename": null, "suffixinstancename": null, "iashost": null }
> 
> Usecase :
> 
> { "aboutThisUseCase": { "name": "Setup trust between SAP IAS and SAP BTP subaccount", "description": "This usecase provides the configuration of services to create trust between a SAP BTP subaccount and a customer IAS tenant", "author": "[fabian.lehmann02@sap.com](mailto:fabian.lehmann02@sap.com)", "testStatus": "tested successfully", "usageStatus": "READY TO BE USED" }, "services": [ { "name": "xsuaa", "plan": "apiaccess", "instancename": "xsuaa_api", "category": "SERVICE", "repeatstatusrequest": 5, "repeatstatustimeout": 200, "createServiceKeys": [ "myServiceKey1" ] } ], "admins": [] }
> 
> Screenshot : <img alt="CF Error" width="615" src="https://user-images.githubusercontent.com/47801828/162207580-ec845ed3-6e74-4bd5-8209-1c89a896eb69.PNG">

Found a fix to this, printed out the results of the following lines of code in btp_cli.py:

result = runCommandAndGetJsonResult(self, command, "INFO", "fetch org name")
parameters = convertStringToJson(result["environmentInstances"][0]["parameters"])
self.accountMetadata = addKeyValuePair(accountMetadata, "org", parameters["instance_name"])

Result returns all the environments as it's intended, but the parameters line converts the first json object in the list, which in my case is my kyma environment. When I set the index to 1, this works as now it's pointing to my CF environment. I'm not sure if my situation is unique in the sense that the returned json object doesn't start with my CF environment, but would it be possible to implement a fix where it looks for the matching CF environment in the returned json object instead of grabbing the first environment in the return list? Thank you.

**Comment by rui1610** [comment] 2022-04-07 14:38
I've just fixed the issue. As I've said that was a code artifact, from the times where btpsa could only do Kyma or CF at a time.

@siluski : can you check whether this update fixed your issue?

@madevr : can you please also check? Maybe your issue is coming from the same root cause (in case you've had more than one CF instance in your subaccount.

**Comment by rui1610** [comment] 2022-04-07 14:47
New image is available now. @siluski & @madevr : you can test now.

**Comment by madevr** [comment] 2022-04-07 15:03
> New image is available now. @siluski & @madevr : you can test now.

I still get the same error.

**Comment by siluski** [comment] 2022-04-07 15:04
> New image is available now. @siluski & @madevr : you can test now.

I just pulled a new container, and the merged changes aren't reflected. I'm going to just comment out the old code and copy and paste the changes you made.

**Comment by siluski** [comment] 2022-04-07 15:30
@rui1610 So with the code that was just recently, merged, there's an error since Kyma runtime environments don't have the properties "Org ID," and "Org Name," these are only in CF. Currently I'm trying to expand the IF statement so that it will only check for these properties if the given environment instance is a CF instance.

**Comment by rui1610** [comment] 2022-04-07 17:35
Yes. That's it. I forgot, that the envInstance needs to be checked, too.

The new docker image is available. Once you start BTPSA you should see the following INFO in the log with the newest Github version of the code:

` INFO       : Git version >f06e7fff18f44e40033e766be0d8e860f6e2fe1f<`

**Comment by siluski** [comment] 2022-04-07 18:33
The github version I'm getting is : 97cba52ed746cd4d1828b685e337431a38edf9b9
There anyway I can get the newest version? I'm using the docker pull command that's specified in the documentation, is there something else I should be doing?

**Comment by rui1610** [comment] 2022-04-08 04:44
No. This is not the right github version (image from 3 days ago). Ideally you should delete the docker container and the respective image and in addition clean the docker cache. Try using the following commands in the command line, before fetching the new container:
`docker container stop   "btp-setup-automator"
docker container rm  -f "btp-setup-automator"
docker image     rmi -f "btp-setup-automator"
docker system prune -a -f`

**Comment by madevr** [comment] 2022-04-08 08:17
I just tested with Git version >5807172c54cd2e05e5723b6f8cc2efe73f71d5ee<, still same error during CF login.

Fixed it locally, this is the PR that would help me (not sure if it breaks anything else):
https://github.com/SAP-samples/btp-setup-automator/pull/62

**Comment by rui1610** [comment] 2022-04-08 08:27
Sounds great. And this is indeed a bug! An artifact from a bigger re-factoring I've done some days ago. Docker image is being re-created and should be there in the next 5 - 10 minutes.

**Closed by rui1610** 2022-04-08 08:27 UTC
Labels: bug
