### ISSUE TITLE
[BUG] For already existing cloudfoundry environment it tries to create new environment

### ISSUE THREAD

**Issue by yevgentrukhin** [SAP-samples/btp-setup-automator#31] opened 2022-03-24 15:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which area is mainly impacted

CLI in general

### Current Behavior

Lets say i have created already certain setup GA/subaccount before, now i want to run the script to add functionality. It is not possible because at the beginning of script it keeps trying to create an environment instance with prepopulated name, the provided subdomain name is not being used as environment instance name.

76f1b"
[2022-03-24 16:03:15] INFO: Create cloudfoundry environment >cloudfoundry-c4uconsumerdevaws<
[2022-03-24 16:03:15] RUN COMMAND: btp --format json create accounts/environment-instance --subaccount "XXXX" --environment cloudfoundry --service cloudfoundry --plan standard --parameters '{"instance_name": "cloudfoundry-c4uconsumerdevaws"}' --landscape "cf-eu10"
[2022-03-24 16:03:17] ERROR: 
[2022-03-24 16:03:17] ERROR: {
  "error": "Environment instances limit for this type has exceeded [Error: 41001/409]"
}

FAILED

### Expected Behavior

parameter file:
    "subaccountname": "AWS [DEV]",
    "subdomain": "c4uconsumerdevaws", <---

It should use exactly the name supplied in subdomain and not adding 'cloudfoundry-' prefix. it should check if it exists, dont create it.

**Comment by yevgentrukhin** [comment] 2022-03-24 15:07
Here is a line of code with a problem: 
        nameOfEnvInstance = accountMetadata["subdomain"] + "_cloudfoundry"
https://github.com/SAP-samples/btp-setup-automator/blob/b8277d901f0053bdcc73a63299a2a8551f32d8bc/libs/python/helperEnvCF.py#L31

**Comment by yevgentrukhin** [comment] 2022-03-24 15:09
If you are ok lets remove "_cloudfoundry"

**Comment by rui1610** [comment] 2022-03-29 06:01
Closing the issue based on my comment above. Please let me know in case of questions.

**Comment by siluski** [comment] 2022-04-06 18:24
Hey all, there's still seems to be an issue regarding this. When you have an existing CF environment and go to add additional apps, services, etc., and you provide a CF org ID, it errors out when it goes to attempt to create a Key-Value pair between org and parameters["instance_name"]. When you run the command : btp --format json list accounts/environment-instances --subaccount <subaccount-id>, there isn't a property called "instance_name", it is instead looking for, "name." On line 366 in btp_cli.py, I changed "instance_name" to "name," and this works. Would it be possible to change that here? Thank you.

**Comment by rui1610** [comment] 2022-04-07 18:32
This was not (hopefully) fixed with the root cause found for https://github.com/SAP-samples/btp-setup-automator/issues/54

**Closed by rui1610** 2022-04-07 18:32 UTC
Labels: bug

**Comment by yevgentrukhin** [comment] 2022-04-07 18:35
If you already used previous version of script, you might need to adjust your usecase file to append _cloudfoundry for env created before. For newly created ones u dont need that suffix.
